git:
  depth: false
go:
  - 1.11
python:
  - 3.6

install:
  # This op is heavy:
  #   Need to get 85.5 MB of archives.
  #   After this operation, 401 MB of additional disk space will be used.
  #
  # - sudo apt-get install -y snapd
  # - sudo snap install hugo
  #
  # Hack to install from deb now.
  - pip install requests Pygments
  - python .travis/hugo_deb.py
  - sudo dpkg -i hugo.deb

script:
  - ".travis/build.sh"
after_success:
  - ".travis/push.sh"

env:
  global:
    # GH_PAT
    secure: RJT3lTdnYTk93T37e+4HGipiRMHYBMKjF3OWSz63yuroD6CWawO1cqSNUY1x9blZ3wV0Tu6OK5q9TsWMSlBdTgLzXto/AyFA75vOdjKftseNzmoDjvYjZNR9MG0xquzlextWa8gmEkYbYUvTwGeCFalj0Yvt2+faa03Lbh5n8O9yFJjiuzntzcpmg8sKSkiUy3GiG45mjDW0q5/2yVUsADfodRZf61OHV9/KrF1tG5UOrpb8ytiSXQY/njXCyAn6CNSmwsYiC7mKejWwsFfw7FBuHlTwTWnfZf1uCGpwCy0nvGW4vYQ2JfD9uQwIzKANxVVZiEuKxUI2SNGwQ2+JOwMoSHi8S5DcyLwp0pASCMXNOK0r4TKE02RHAUyfaUQ/mu9tYHpzZOJ/lzXcH0vml4bODH4d32LLjsYZGnU1cq92V4X8V1klzcCKQ0s0L+7Y291Jh0w78VmkZRU/CLcitt32Mpc708DuX13STgPgqarMzPojYJvWtl0VIYVI9N/biXq6o5NuWkEBoREGhRBnCH63orV1dO/8Twu3x1KnPwVau6chTEe/ey3/J2Za1g+iLgqbIIp0o5OZvba5AbJE+0fSifH0FMn353FiOm5BqDbv5uPCZl96SOxAM4G7TLOh0mQ5wzlWpOUo6iL31QA9qTeMlA3YfgUY7QNb5/MBj0k=
